# /config/packages/knp_snappy.yml
knp_snappy:
  pdf:
    enabled:    true
    binary:     '%env(WKHTMLTOPDF_PATH)%'
    options:    []
  image:
    enabled:    true
    binary:     '%env(WKHTMLTOIMAGE_PATH)%'
    options:    []